### PR TITLE
Use a Counter module for credits to allow simultaneous enq/deq operations

### PR DESCRIPTION
**Pull request by krame505**
See discussion in #22.

### CODE REVIEW

**Comment by krame505** [comment]
The tests are currently failing, but I'm currently reproduce locally - see https://github.com/B-Lang-org/bsc/issues/669.

**Comment by krame505** [comment]
Should be fixed now - there was some nondeterminism in the GenCMsg tests causing failures after I deconflicted the tx/rx sides.

**Comment by quark17** [comment]
Is there a reason that you used `mkDWire` and a rule instead of using `mkCReg`?  I'm just concerned that the wire/rule version doesn't have any scheduling protection, so the user is on their own to reason that they're making correct use of the reading of the value relative to the incr/decr.  (At the very least, I think the `update` rule should have `fire_when_enabled` and `always_enabled` assertions, to guarantee that the effects of inc/dec do happen.)

**Comment by krame505** [comment]
Good point - done.

**Pull request merged**
